### ISSUE TITLE
Fix "data breach" warning on sign-in

### ISSUE THREAD

**Issue by MrM117** [googleinterns/step157-2020#27]
![image](https://user-images.githubusercontent.com/29340463/89930512-dddeb380-dbd8-11ea-8fe1-6242aa71a18e.png)

Steps to reproduce:
- Create account
- Attempt to sign in

My _guess_ is that the password is not handled securely in the client, and the Google vulnerability detection extension is picking up on a local vulnerability. Another possibility is that the Firebase database is not locked down (see #22 ).

**Comment by MrM117** [comment]
I would probably start by fixing #22 , and if that doesn't eliminate this warning, we can try to debug further.

**Comment by hack-heart** [comment]
I found this https://support.google.com/chrome/thread/23534509?hl=en&msgid=23534509

It looks like this is a new feature of Chrome that keeps track of password leaks, so weak/common passwords are likely to cause this on any application. I created an account with a strong password and did not run into this.

We still need to fix #22 though!

**Comment by MrM117** [comment]
Ah, good catch! I searched for it, but only internally, because I assumed it was an internal tool... Thanks, Chibuzo!
